name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations
        run: |
          touch /tmp/untranslated-messages.json
          flutter gen-l10n --untranslated-messages-file=/tmp/untranslated-messages.json
          jq -e 'length == 0' /tmp/untranslated-messages.json >/dev/null

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

